export interface LegalSection {
  id: string;
  act: 'IPC' | 'BNSS' | 'BSA' | 'CrPC' | 'CPC';
  section: string;
  title: string;
  description: string;
  punishment?: string;
  bailable?: boolean;
  cognizable?: boolean;
}

export const legalSections: LegalSection[] = [
  // IPC Sections
  { id:'ipc-302', act:'IPC', section:'302', title:'Murder', description:'Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine.', punishment:'Death or Life Imprisonment + Fine', bailable:false, cognizable:true },
  { id:'ipc-304', act:'IPC', section:'304', title:'Culpable Homicide not amounting to Murder', description:'Punishment for culpable homicide not amounting to murder. If act by which death is caused is done with intention of causing death — imprisonment for life or up to 10 years + fine.', punishment:'Life or 10 years + Fine', bailable:false, cognizable:true },
  { id:'ipc-304b', act:'IPC', section:'304B', title:'Dowry Death', description:'Where death of woman caused by burns, bodily injury within 7 years of marriage and shown she was subjected to cruelty by husband or relatives in connection with demand for dowry.', punishment:'Min 7 years to Life', bailable:false, cognizable:true },
  { id:'ipc-306', act:'IPC', section:'306', title:'Abetment of Suicide', description:'If any person commits suicide, whoever abets the commission of such suicide, shall be punished with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.', punishment:'Up to 10 years + Fine', bailable:false, cognizable:true },
  { id:'ipc-307', act:'IPC', section:'307', title:'Attempt to Murder', description:'Whoever does any act with such intention or knowledge, and under such circumstances that, if he by that act caused death, he would be guilty of murder.', punishment:'Up to 10 years or Life if hurt caused', bailable:false, cognizable:true },
  { id:'ipc-308', act:'IPC', section:'308', title:'Attempt to commit Culpable Homicide', description:'Whoever does any act with such intention or knowledge and under such circumstances that, if he by that act caused death, he would be guilty of culpable homicide not amounting to murder.', punishment:'Up to 3 years or 7 years if hurt', bailable:false, cognizable:true },
  { id:'ipc-323', act:'IPC', section:'323', title:'Voluntarily Causing Hurt', description:'Whoever, except in the case provided for by section 334, voluntarily causes hurt, shall be punished with imprisonment of either description for a term which may extend to one year, or with fine which may extend to one thousand rupees, or with both.', punishment:'Up to 1 year or Fine up to Rs.1000', bailable:true, cognizable:false },
  { id:'ipc-324', act:'IPC', section:'324', title:'Voluntarily Causing Hurt by Dangerous Weapons', description:'Whoever, except in the case provided for by section 334, voluntarily causes hurt by means of any instrument for shooting, stabbing or cutting, or any instrument which, used as a weapon of offence, is likely to cause death.', punishment:'Up to 3 years or Fine or Both', bailable:false, cognizable:true },
  { id:'ipc-325', act:'IPC', section:'325', title:'Voluntarily Causing Grievous Hurt', description:'Whoever, except in the case provided for by section 335, voluntarily causes grievous hurt, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.', punishment:'Up to 7 years + Fine', bailable:false, cognizable:true },
  { id:'ipc-354', act:'IPC', section:'354', title:'Assault or Criminal Force to Woman with Intent to Outrage her Modesty', description:'Whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likely that he will thereby outrage her modesty, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.', punishment:'Up to 2 years or Fine or Both', bailable:false, cognizable:true },
  { id:'ipc-354a', act:'IPC', section:'354A', title:'Sexual Harassment', description:'Physical contact and advances involving unwelcome and explicit sexual overtures; demand or request for sexual favours; showing pornography against will; making sexually coloured remarks.', punishment:'Up to 3 years or Fine or Both', bailable:false, cognizable:false },
  { id:'ipc-354d', act:'IPC', section:'354D', title:'Stalking', description:'Any man who follows a woman and contacts, or attempts to contact such woman to foster personal interaction repeatedly despite a clear indication of disinterest; or monitors the use by a woman of the internet, email or any other form of electronic communication.', punishment:'Up to 3 years (1st offence), Up to 5 years (subsequent)', bailable:false, cognizable:true },
  { id:'ipc-376', act:'IPC', section:'376', title:'Punishment for Rape', description:'Whoever commits rape shall be punished with rigorous imprisonment of either description for a term which shall not be less than ten years, but which may extend to imprisonment for life, and shall also be liable to fine.', punishment:'Min 10 years to Life + Fine', bailable:false, cognizable:true },
  { id:'ipc-379', act:'IPC', section:'379', title:'Punishment for Theft', description:'Whoever commits theft shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.', punishment:'Up to 3 years or Fine or Both', bailable:true, cognizable:true },
  { id:'ipc-380', act:'IPC', section:'380', title:'Theft in Dwelling House', description:'Whoever commits theft in any building, tent or vessel, which building, tent or vessel is used as a human dwelling, or used for the custody of property, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.', punishment:'Up to 7 years + Fine', bailable:false, cognizable:true },
  { id:'ipc-392', act:'IPC', section:'392', title:'Punishment for Robbery', description:'Whoever commits robbery shall be punished with rigorous imprisonment for a term which may extend to ten years, and shall also be liable to fine; and, if the robbery be committed on the highway between sunset and sunrise, the imprisonment may be extended to fourteen years.', punishment:'Up to 10 years + Fine (14 years on highway)', bailable:false, cognizable:true },
  { id:'ipc-395', act:'IPC', section:'395', title:'Punishment for Dacoity', description:'Whoever commits dacoity shall be punished with imprisonment for life, or with rigorous imprisonment for a term which may extend to ten years, and shall also be liable to fine.', punishment:'Life or Up to 10 years + Fine', bailable:false, cognizable:true },
  { id:'ipc-406', act:'IPC', section:'406', title:'Criminal Breach of Trust', description:'Whoever commits criminal breach of trust shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.', punishment:'Up to 3 years or Fine or Both', bailable:false, cognizable:true },
  { id:'ipc-409', act:'IPC', section:'409', title:'Criminal Breach of Trust by Public Servant', description:'Whoever, being in any manner entrusted with property, or with any dominion over property in his capacity of a public servant, or in the way of his business as a banker, merchant, factor, broker, attorney or agent, commits criminal breach of trust in respect of that property.', punishment:'Life or Up to 10 years + Fine', bailable:false, cognizable:true },
  { id:'ipc-420', act:'IPC', section:'420', title:'Cheating and Dishonestly Inducing Delivery of Property', description:'Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, or anything which is signed or sealed, and which is capable of being converted into a valuable security.', punishment:'Up to 7 years + Fine', bailable:false, cognizable:true },
  { id:'ipc-425', act:'IPC', section:'425', title:'Mischief', description:'Whoever with intent to cause, or knowing that he is likely to cause, wrongful loss or damage to the public or to any person, causes the destruction of any property, or any such change in any property or in the situation thereof as destroys or diminishes its value or utility, or affects it injuriously, commits mischief.', punishment:'Up to 3 months or Fine or Both', bailable:true, cognizable:false },
  { id:'ipc-427', act:'IPC', section:'427', title:'Mischief causing damage to the amount of fifty rupees', description:'Whoever commits mischief and thereby causes loss or damage to the amount of fifty rupees or upwards, shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.', punishment:'Up to 2 years or Fine or Both', bailable:true, cognizable:false },
  { id:'ipc-447', act:'IPC', section:'447', title:'Punishment for Criminal Trespass', description:'Whoever commits criminal trespass shall be punished with imprisonment of either description for a term which may extend to three months, or with fine which may extend to five hundred rupees, or with both.', punishment:'Up to 3 months or Fine up to Rs.500', bailable:true, cognizable:false },
  { id:'ipc-498a', act:'IPC', section:'498A', title:'Husband or relative subjecting woman to cruelty', description:'Whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty shall be punished with imprisonment for a term which may extend to three years and shall also be liable to fine.', punishment:'Up to 3 years + Fine', bailable:false, cognizable:true },
  { id:'ipc-504', act:'IPC', section:'504', title:'Intentional Insult with intent to provoke breach of peace', description:'Whoever intentionally insults, and thereby gives provocation to any person, intending or knowing it to be likely that such provocation will cause him to break the public peace, or to commit any other offence.', punishment:'Up to 2 years or Fine or Both', bailable:true, cognizable:false },
  { id:'ipc-506', act:'IPC', section:'506', title:'Punishment for Criminal Intimidation', description:'Whoever commits the offence of criminal intimidation shall be punished with imprisonment of either description for a term which may extend to two years, or with fine, or with both.', punishment:'Up to 2 years or Fine or Both', bailable:true, cognizable:false },
  { id:'ipc-509', act:'IPC', section:'509', title:'Word, gesture or act intended to insult modesty of woman', description:'Whoever, intending to insult the modesty of any woman, utters any word, makes any sound or gesture, or exhibits any object, intending that such word or sound shall be heard, or that such gesture or object shall be seen, by such woman, or intrudes upon the privacy of such woman.', punishment:'Up to 3 years or Fine or Both', bailable:true, cognizable:true },

  // BNSS Sections
  { id:'bnss-173', act:'BNSS', section:'173', title:'FIR — Information in cognizable cases', description:'Every information relating to the commission of a cognizable offence, if given orally to an officer in charge of a police station, shall be reduced to writing by him or under his direction, and be read over to the informant.', bailable:false, cognizable:true },
  { id:'bnss-187', act:'BNSS', section:'187', title:'Remand — Detention of accused', description:'Whenever any person is arrested and detained in custody, and it appears that the investigation cannot be completed within the period of twenty-four hours fixed by section 58, and there are grounds for believing that the accusation or information is well-founded.', bailable:false, cognizable:true },
  { id:'bnss-436', act:'BNSS', section:'436', title:'Bail in bailable offences', description:'When any person other than a person accused of a non-bailable offence is arrested or detained without warrant by an officer in charge of a police station, or appears or is brought before a Court, and is prepared at any time while in the custody of such officer or at any stage of the proceeding before such Court to give bail.', bailable:true, cognizable:false },
  { id:'bnss-437', act:'BNSS', section:'437', title:'Bail in non-bailable offences', description:'When any person accused of, or suspected of, the commission of any non-bailable offence is arrested or detained without warrant by an officer in charge of a police station or appears or is brought before a Court other than the High Court or Court of Session.', bailable:false, cognizable:true },
  { id:'bnss-438', act:'BNSS', section:'438', title:'Anticipatory Bail', description:'Direction for grant of bail to person apprehending arrest. When any person has reason to believe that he may be arrested on accusation of having committed a non-bailable offence, he may apply to the High Court or the Court of Session for a direction under this section.', bailable:false, cognizable:false },
  { id:'bnss-439', act:'BNSS', section:'439', title:'Special powers of High Court or Court of Session regarding bail', description:'A High Court or Court of Session may direct that any person accused of an offence and in custody be released on bail, and if the offence is of the nature specified in subsection of section 437, may impose any condition which it considers necessary for the purposes mentioned in that section.', bailable:false, cognizable:false },
  { id:'bnss-482', act:'BNSS', section:'482', title:'Saving of inherent powers of High Court', description:'Nothing in this Sanhita shall be deemed to limit or affect the inherent powers of the High Court to make such orders as may be necessary to give effect to any order under this Sanhita, or to prevent abuse of the process of any Court or otherwise to secure the ends of justice.', bailable:false, cognizable:false },

  // BSA (Bharatiya Sakshya Adhiniyam)
  { id:'bsa-25', act:'BSA', section:'25', title:'Confession to police officer not to be proved', description:'No confession made to a police officer shall be proved as against a person accused of any offence.', bailable:false, cognizable:false },
  { id:'bsa-26', act:'BSA', section:'26', title:'Confession by accused while in custody of police', description:'No confession made by any person whilst he is in the custody of a police officer, unless it be made in the immediate presence of a Magistrate, shall be proved as against such person.', bailable:false, cognizable:false },
  { id:'bsa-63', act:'BSA', section:'63', title:'Secondary Evidence', description:'Secondary evidence includes: certified copies; copies made from the original by mechanical processes which in themselves ensure the accuracy of the copy; copies made from or compared with the original; counterparts of documents as against the parties who did not execute them; oral accounts of the contents of a document given by some person who has himself seen it.', bailable:false, cognizable:false },
  { id:'bsa-65b', act:'BSA', section:'65B', title:'Admissibility of Electronic Records', description:'Any information contained in an electronic record which is printed on a paper, stored, recorded or copied in optical or magnetic media produced by a computer shall be deemed to be also a document, if the conditions mentioned in this section are satisfied in relation to the information and computer in question.', bailable:false, cognizable:false },

  // CPC Sections
  { id:'cpc-9', act:'CPC', section:'9', title:'Courts to try all civil suits unless barred', description:'The Courts shall (subject to the provisions herein contained) have jurisdiction to try all suits of a civil nature excepting suits of which their cognizance is either expressly or impliedly barred.', bailable:false, cognizable:false },
  { id:'cpc-80', act:'CPC', section:'80', title:'Notice before suit against Government', description:'Save as otherwise provided in sub-section (2), no suit shall be instituted against the Government or against a public officer in respect of any act purporting to be done by such public officer in his official capacity, until the expiration of two months next after notice in writing has been delivered to, or left at the office of.', bailable:false, cognizable:false },
  { id:'cpc-96', act:'CPC', section:'96', title:'Appeal from original decree', description:'Save where otherwise expressly provided in the body of this Code or by any other law for the time being in force, an appeal shall lie from every decree passed by any Court exercising original jurisdiction to the Court authorised to hear appeals from the decisions of such Court.', bailable:false, cognizable:false },
  { id:'cpc-115', act:'CPC', section:'115', title:'Revision', description:'The High Court may call for the record of any case which has been decided by any Court subordinate to such High Court and in which no appeal lies thereto, and if such subordinate Court appears to have exercised a jurisdiction not vested in it by law, or to have failed to exercise a jurisdiction so vested.', bailable:false, cognizable:false },
  { id:'cpc-151', act:'CPC', section:'151', title:'Saving of inherent powers of Court', description:'Nothing in this Code shall be deemed to limit or otherwise affect the inherent power of the Court to make such orders as may be necessary for the ends of justice or to prevent abuse of the process of the Court.', bailable:false, cognizable:false },
];

export const searchSections = (query: string): LegalSection[] => {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return legalSections.filter(s =>
    s.section.toLowerCase().includes(q) ||
    s.title.toLowerCase().includes(q) ||
    s.description.toLowerCase().includes(q) ||
    s.act.toLowerCase().includes(q) ||
    (s.punishment && s.punishment.toLowerCase().includes(q))
  ).slice(0, 20);
};

export const getSectionsByAct = (act: LegalSection['act']): LegalSection[] =>
  legalSections.filter(s => s.act === act);
